### ISSUE TITLE
Rendering image size attributes

### ISSUE THREAD

**Issue by Sebobo** [jonnitto/Jonnitto.Image#1]
This is a (multiple allowed):
* [x] bug
* [x] enhancement

* Version: all

### What you did
Just use it ;)

### Expected Behavior
I expect the image tags to have width and height attributes. 
Those help the browser to render the layout more precisely on initial load and for example are required to render images with AMP.

### Actual Behavior
The attributes are missing.

I know that when rendering image uris just return the uri and not the final size of an image.
But this could be solved for example like with this helper https://github.com/Sebobo/Shel.Blog/blob/master/Classes/Fusion/Helper/AssetHelper.php
and usage here https://github.com/Sebobo/Shel.Blog/blob/9995e1fe7cf59e71a6b1d5ba5400b2dacd6a853a/Resources/Private/Templates/FusionObjects/BlogFeedEntry.atom#L24

**Comment by jonnitto** [comment]
Would you like to do a PR?

**Comment by Sebobo** [comment]
That's still my plan :)

**Comment by jonnitto** [comment]
If the new version of Carbon.Image is used the width and height are set.
